'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { Home, Users, ClipboardList, Target, CalendarDays, CheckSquare, Newspaper, BarChart3, LogOut, Plus, Search, Menu, X, Building2, MapPin, Euro, Pencil, Trash2, ChevronLeft, ChevronRight, Clock, Phone, Mail } from 'lucide-react';

type Module = 'inicio'|'inmuebles'|'clientes'|'pedidos'|'captacion'|'calendario'|'tareas'|'noticias'|'estadisticas';
type Modal = null|'property'|'client'|'event';
const modules = [
 {id:'inicio',label:'Inicio',icon:Home},{id:'inmuebles',label:'Inmuebles',icon:Building2},{id:'clientes',label:'Clientes',icon:Users},
 {id:'pedidos',label:'Pedidos',icon:ClipboardList},{id:'captacion',label:'Captación',icon:Target},{id:'calendario',label:'Calendario',icon:CalendarDays},
 {id:'tareas',label:'Tareas',icon:CheckSquare},{id:'noticias',label:'Noticias',icon:Newspaper},{id:'estadisticas',label:'Estadísticas',icon:BarChart3}
] as const;
const money = (n:any) => n ? new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n)) : 'Consultar';
const dateKey = (d:Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;

export default function Page(){
 const [session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[module,setModule]=useState<Module>('inicio'),[menu,setMenu]=useState(false),[search,setSearch]=useState('');
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
 const [properties,setProperties]=useState<any[]>([]),[clients,setClients]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]);
 const [modal,setModal]=useState<Modal>(null),[editing,setEditing]=useState<any>(null),[saving,setSaving]=useState(false);
 const [calendarDate,setCalendarDate]=useState(new Date()); const [selectedDay,setSelectedDay]=useState(dateKey(new Date()));
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadData()},[session]);
 async function loadData(){const [p,c,e]=await Promise.all([supabase.from('properties').select('*').order('created_at',{ascending:false}),supabase.from('clients').select('*').order('created_at',{ascending:false}),supabase.from('events').select('*').order('start_at',{ascending:true})]);setProperties(p.data||[]);setClients(c.data||[]);setEvents(e.data||[])}
 async function signIn(e:React.FormEvent){e.preventDefault();setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message)}
 async function saveProperty(f:FormData){setSaving(true);setError('');const {data:user}=await supabase.auth.getUser();const payload:any={owner_id:user.user?.id,title:f.get('title'),property_type:f.get('type'),city:f.get('city'),address:f.get('address'),price:Number(f.get('price')||0),status:f.get('status'),visibility:f.get('visibility'),bedrooms:Number(f.get('bedrooms')||0)||null,bathrooms:Number(f.get('bathrooms')||0)||null,area_m2:Number(f.get('area')||0)||null,description:f.get('description')};const q=editing?supabase.from('properties').update(payload).eq('id',editing.id):supabase.from('properties').insert(payload);const {error}=await q;if(error)setError(error.message);else{setModal(null);setEditing(null);await loadData()}setSaving(false)}
 async function saveClient(f:FormData){setSaving(true);setError('');const {data:user}=await supabase.auth.getUser();const payload={owner_id:user.user?.id,name:f.get('name'),email:f.get('email'),phone:f.get('phone'),city:f.get('city'),notes:f.get('notes')};const q=editing?supabase.from('clients').update(payload).eq('id',editing.id):supabase.from('clients').insert(payload);const {error}=await q;if(error)setError(error.message);else{setModal(null);setEditing(null);await loadData()}setSaving(false)}
 async function saveEvent(f:FormData){setSaving(true);setError('');const {data:user}=await supabase.auth.getUser();const start=f.get('start') as string;const end=f.get('end') as string;const payload={owner_id:user.user?.id,title:f.get('title'),start_at:new Date(start).toISOString(),end_at:end?new Date(end).toISOString():null,location:f.get('location'),notes:f.get('notes')};const q=editing?supabase.from('events').update(payload).eq('id',editing.id):supabase.from('events').insert(payload);const {error}=await q;if(error)setError(error.message);else{setModal(null);setEditing(null);await loadData()}setSaving(false)}
 async function remove(table:string,id:string){if(!confirm('¿Seguro que quieres eliminar este registro?'))return;const {error}=await supabase.from(table).delete().eq('id',id);if(error)setError(error.message);else await loadData()}
 function open(m:Modal,row:any=null){setError('');setEditing(row);setModal(m)}
 if(loading)return <div className="splash">Cargando Vive Bilbao CRM…</div>;
 if(!session)return <main className="login"><div className="login-card"><div className="brand"><b>VIVE</b> BILBAO <small>INMOBILIARIO</small></div><h1>Acceso al CRM</h1><p>Entra con tu usuario profesional.</p><form onSubmit={signIn}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button className="primary">Entrar</button></form></div></main>;
 const filteredProperties=properties.filter(p=>JSON.stringify(p).toLowerCase().includes(search.toLowerCase())); const filteredClients=clients.filter(c=>JSON.stringify(c).toLowerCase().includes(search.toLowerCase()));
 return <div className="shell"><aside className={menu?'sidebar open':'sidebar'}><div className="logo"><b>VIVE</b> BILBAO<small>INMOBILIARIO</small></div><nav>{modules.map(m=><button className={module===m.id?'nav active':'nav'} key={m.id} onClick={()=>{setModule(m.id);setMenu(false)}}><m.icon size={18}/>{m.label}</button>)}</nav><button className="nav logout" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/>Cerrar sesión</button></aside>
 <section className="main"><header><button className="mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div><strong>{modules.find(m=>m.id===module)?.label}</strong><span>CRM Vive Bilbao Inmobiliario</span></div><div className="header-actions"><div className="search"><Search size={16}/><input placeholder="Buscar…" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="primary small" onClick={()=>open(module==='clientes'?'client':module==='calendario'?'event':'property')}><Plus size={16}/> Nuevo</button></div></header>
 <div className="content">
 {module==='inicio'&&<Dashboard properties={properties} clients={clients} events={events} onGo={setModule}/>} 
 {module==='inmuebles'&&<PropertyList rows={filteredProperties} onNew={()=>open('property')} onEdit={r=>open('property',r)} onDelete={r=>remove('properties',r.id)}/>} 
 {module==='clientes'&&<ClientList rows={filteredClients} onNew={()=>open('client')} onEdit={r=>open('client',r)} onDelete={r=>remove('clients',r.id)}/>} 
 {module==='calendario'&&<CalendarView events={events} month={calendarDate} setMonth={setCalendarDate} selected={selectedDay} setSelected={setSelectedDay} onNew={(day)=>{setSelectedDay(day);open('event')}} onEdit={r=>open('event',r)} onDelete={r=>remove('events',r.id)}/>} 
 {module==='pedidos'&&<Empty title="Pedidos" text="Próximo módulo: necesidades de compra/alquiler y cruces automáticos con inmuebles."/>}
 {module==='captacion'&&<Empty title="Captación" text="Próximo módulo: propietarios, valoraciones, seguimiento y embudo de captación."/>}
 {module==='tareas'&&<Empty title="Tareas" text="Próximo módulo: tareas por asesor, vencimientos y seguimiento."/>}
 {module==='noticias'&&<Empty title="Noticias" text="Próximo módulo: noticias y comunicaciones internas."/>}
 {module==='estadisticas'&&<Stats properties={properties} clients={clients} events={events}/>} 
 </div></section>
 {modal==='property'&&<PropertyModal row={editing} onClose={()=>{setModal(null);setEditing(null)}} onSave={saveProperty} saving={saving} error={error}/>} 
 {modal==='client'&&<ClientModal row={editing} onClose={()=>{setModal(null);setEditing(null)}} onSave={saveClient} saving={saving} error={error}/>} 
 {modal==='event'&&<EventModal row={editing} defaultDay={selectedDay} onClose={()=>{setModal(null);setEditing(null)}} onSave={saveEvent} saving={saving} error={error}/>} 
 </div>
}

function Dashboard({properties,clients,events,onGo}:{properties:any[],clients:any[],events:any[],onGo:(m:Module)=>void}){return <><div className="hero"><div><span className="eyebrow">Panel profesional</span><h1>Buenos días 👋</h1><p>Gestiona clientes, inmuebles y agenda desde un solo lugar.</p></div></div><div className="kpis"><Kpi icon={<Building2/>} label="Inmuebles" value={properties.length}/><Kpi icon={<Users/>} label="Clientes" value={clients.length}/><Kpi icon={<Target/>} label="Captaciones" value="0"/><Kpi icon={<CalendarDays/>} label="Eventos" value={events.length}/></div><div className="two"><div className="panel"><h2>Accesos rápidos</h2><div className="quick"><button onClick={()=>onGo('inmuebles')}><Building2/> Inmuebles</button><button onClick={()=>onGo('clientes')}><Users/> Clientes</button><button onClick={()=>onGo('captacion')}><Target/> Captación</button><button onClick={()=>onGo('calendario')}><CalendarDays/> Calendario</button></div></div><div className="panel"><h2>Próximas citas</h2>{events.slice(0,5).map(e=><div className="mini-event" key={e.id}><b>{e.title}</b><span>{new Date(e.start_at).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'})}</span></div>)}{!events.length&&<p className="muted">Todavía no hay eventos.</p>}</div></div></>}
function Kpi({icon,label,value}:{icon:any,label:string,value:any}){return <div className="kpi">{icon}<div><span>{label}</span><strong>{value}</strong></div></div>}
function PropertyList({rows,onNew,onEdit,onDelete}:{rows:any[],onNew:()=>void,onEdit:(r:any)=>void,onDelete:(r:any)=>void}){return <><div className="toolbar"><div><h1>Inmuebles</h1><p>{rows.length} registros visibles · compartidos y privados</p></div><button className="primary" onClick={onNew}><Plus size={18}/> Nuevo inmueble</button></div>{rows.length?<div className="grid">{rows.map(p=><article className="property" key={p.id}><div className="photo"><Building2 size={32}/><span>{p.status||'active'}</span></div><div className="property-body"><h3>{p.title}</h3><p><MapPin size={14}/> {p.city||'—'} {p.address?`· ${p.address}`:''}</p><strong>{money(p.price)}</strong><small>{p.property_type||'Inmueble'} {p.area_m2?`· ${p.area_m2} m²`:''} {p.bedrooms?`· ${p.bedrooms} hab.`:''}</small><div className="card-actions"><button onClick={()=>onEdit(p)}><Pencil size={15}/> Editar</button><button className="danger" onClick={()=>onDelete(p)}><Trash2 size={15}/> Eliminar</button></div></div></article>)}</div>:<div className="empty panel"><Building2 size={35}/><h3>No hay inmuebles todavía</h3><p>Registra pisos, casas, chalets, parcelas, locales o garajes.</p><button className="primary" onClick={onNew}><Plus size={16}/> Añadir inmueble</button></div>}</>}
function ClientList({rows,onNew,onEdit,onDelete}:{rows:any[],onNew:()=>void,onEdit:(r:any)=>void,onDelete:(r:any)=>void}){return <div className="panel page-panel"><div className="panel-title"><div><h1>Clientes</h1><p className="muted">{rows.length} clientes visibles</p></div><button className="primary small" onClick={onNew}><Plus size={16}/> Nuevo cliente</button></div>{rows.length?<div className="rows">{rows.map(r=><div className="row" key={r.id}><div><b>{r.name}</b><span>{r.city||''} {r.phone?`· ${r.phone}`:''} {r.email?`· ${r.email}`:''}</span></div><div className="row-actions"><button onClick={()=>onEdit(r)}><Pencil size={15}/></button><button className="danger" onClick={()=>onDelete(r)}><Trash2 size={15}/></button></div></div>)}</div>:<div className="empty"><Users size={35}/><h3>No hay clientes todavía</h3><p>Añade propietarios, compradores, vendedores o contactos.</p><button className="primary" onClick={onNew}><Plus size={16}/> Nuevo cliente</button></div>}</div>}
function CalendarView({events,month,setMonth,selected,setSelected,onNew,onEdit,onDelete}:{events:any[],month:Date,setMonth:(d:Date)=>void,selected:string,setSelected:(s:string)=>void,onNew:(s:string)=>void,onEdit:(r:any)=>void,onDelete:(r:any)=>void}){const first=new Date(month.getFullYear(),month.getMonth(),1);const start=(first.getDay()+6)%7;const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const cells=Array.from({length:Math.ceil((start+days)/7)*7},(_,i)=>{const n=i-start+1;return n>0&&n<=days?new Date(month.getFullYear(),month.getMonth(),n):null});const dayEvents=events.filter(e=>dateKey(new Date(e.start_at))===selected);return <><div className="toolbar"><div><h1>Calendario</h1><p>Agenda completa con todos los días del mes.</p></div><button className="primary" onClick={()=>onNew(selected)}><Plus size={18}/> Nueva cita</button></div><div className="calendar-layout"><div className="calendar panel"><div className="cal-head"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><h2>{month.toLocaleDateString('es-ES',{month:'long',year:'numeric'})}</h2><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></div><div className="weekdays">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=><b key={x}>{x}</b>)}</div><div className="calendar-grid">{cells.map((d,i)=>{if(!d)return <div className="cal-cell muted-cell" key={i}/>;const k=dateKey(d), has=events.some(e=>dateKey(new Date(e.start_at))===k);return <button key={k} className={selected===k?'cal-cell selected':'cal-cell'} onClick={()=>setSelected(k)}><span>{d.getDate()}</span>{has&&<i/>}</button>})}</div></div><div className="panel day-panel"><div className="day-title"><div><span className="eyebrow">Agenda del día</span><h2>{new Date(selected+'T12:00:00').toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</h2></div><button className="primary small" onClick={()=>onNew(selected)}><Plus size={15}/> Añadir</button></div>{dayEvents.length?dayEvents.map(e=><div className="event-card" key={e.id}><div><b>{e.title}</b><span><Clock size={13}/> {new Date(e.start_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}{e.location?` · ${e.location}`:''}</span>{e.notes&&<small>{e.notes}</small>}</div><div className="row-actions"><button onClick={()=>onEdit(e)}><Pencil size={15}/></button><button className="danger" onClick={()=>onDelete(e)}><Trash2 size={15}/></button></div></div>):<div className="empty"><CalendarDays size={34}/><p>No hay citas para este día.</p></div>}</div></div></>}
function PropertyModal({row,onClose,onSave,saving,error}:{row:any,onClose:()=>void,onSave:(f:FormData)=>void,saving:boolean,error:string}){return <Modal title={row?'Editar inmueble':'Nuevo inmueble'} onClose={onClose}><form className="form-grid" onSubmit={e=>{e.preventDefault();onSave(new FormData(e.currentTarget))}}><label>Título<input name="title" required defaultValue={row?.title||''} placeholder="Ej. Piso en Indautxu"/></label><label>Tipo<select name="type" defaultValue={row?.property_type||'Piso'}>{['Piso','Casa','Chalet','Parcela','Local','Garaje','Oficina','Terreno'].map(x=><option key={x}>{x}</option>)}</select></label><label>Ciudad<input name="city" required defaultValue={row?.city||'Bilbao'}/></label><label>Dirección<input name="address" defaultValue={row?.address||''}/></label><label>Precio (€)<input name="price" type="number" min="0" defaultValue={row?.price||''}/></label><label>Estado<select name="status" defaultValue={row?.status||'active'}><option value="active">Activo</option><option value="reserved">Reservado</option><option value="sold">Vendido</option><option value="rented">Alquilado</option><option value="inactive">Inactivo</option></select></label><label>Visibilidad<select name="visibility" defaultValue={row?.visibility||'shared'}><option value="shared">Compartido con el equipo</option><option value="private">Privado</option></select></label><label>Superficie m²<input name="area" type="number" min="0" defaultValue={row?.area_m2||''}/></label><label>Habitaciones<input name="bedrooms" type="number" min="0" defaultValue={row?.bedrooms||''}/></label><label>Baños<input name="bathrooms" type="number" min="0" defaultValue={row?.bathrooms||''}/></label><label className="full">Descripción<textarea name="description" rows={4} defaultValue={row?.description||''}/></label>{error&&<div className="error full">{error}</div>}<button className="primary full" disabled={saving}>{saving?'Guardando…':row?'Guardar cambios':'Guardar inmueble'}</button></form></Modal>}
function ClientModal({row,onClose,onSave,saving,error}:{row:any,onClose:()=>void,onSave:(f:FormData)=>void,saving:boolean,error:string}){return <Modal title={row?'Editar cliente':'Nuevo cliente'} onClose={onClose}><form className="form-grid" onSubmit={e=>{e.preventDefault();onSave(new FormData(e.currentTarget))}}><label>Nombre completo<input name="name" required defaultValue={row?.name||''}/></label><label>Ciudad<input name="city" defaultValue={row?.city||'Bilbao'}/></label><label><span><Phone size={13}/> Teléfono</span><input name="phone" defaultValue={row?.phone||''}/></label><label><span><Mail size={13}/> Email</span><input name="email" type="email" defaultValue={row?.email||''}/></label><label className="full">Notas<textarea name="notes" rows={5} defaultValue={row?.notes||''}/></label>{error&&<div className="error full">{error}</div>}<button className="primary full" disabled={saving}>{saving?'Guardando…':row?'Guardar cambios':'Guardar cliente'}</button></form></Modal>}
function EventModal({row,defaultDay,onClose,onSave,saving,error}:{row:any,defaultDay:string,onClose:()=>void,onSave:(f:FormData)=>void,saving:boolean,error:string}){const localStart=row?new Date(row.start_at):new Date(`${defaultDay}T10:00`);const localEnd=row?.end_at?new Date(row.end_at):new Date(`${defaultDay}T11:00`);const fmt=(d:Date)=>{const p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};return <Modal title={row?'Editar cita':'Nueva cita'} onClose={onClose}><form className="form-grid" onSubmit={e=>{e.preventDefault();onSave(new FormData(e.currentTarget))}}><label className="full">Título<input name="title" required defaultValue={row?.title||''} placeholder="Ej. Visita piso Indautxu"/></label><label>Inicio<input name="start" type="datetime-local" required defaultValue={fmt(localStart)}/></label><label>Fin<input name="end" type="datetime-local" defaultValue={fmt(localEnd)}/></label><label>Ubicación<input name="location" defaultValue={row?.location||''}/></label><label className="full">Notas<textarea name="notes" rows={4} defaultValue={row?.notes||''}/></label>{error&&<div className="error full">{error}</div>}<button className="primary full" disabled={saving}>{saving?'Guardando…':row?'Guardar cambios':'Guardar cita'}</button></form></Modal>}
function Modal({title,onClose,children}:{title:string,onClose:()=>void,children:React.ReactNode}){return <div className="modal-back"><div className="modal"><button className="close" onClick={onClose}><X/></button><h2>{title}</h2>{children}</div></div>}
function Empty({title,text}:{title:string,text:string}){return <div className="panel page-panel"><div className="panel-title"><h1>{title}</h1></div><div className="empty"><Target size={34}/><h3>{title}</h3><p>{text}</p></div></div>}
function Stats({properties,clients,events}:{properties:any[],clients:any[],events:any[]}){const avg=properties.length?Math.round(properties.reduce((a,p)=>a+(Number(p.price)||0),0)/properties.length):0;return <><div className="toolbar"><div><h1>Estadísticas</h1><p>Visión rápida de actividad.</p></div></div><div className="kpis"><Kpi icon={<Building2/>} label="Inmuebles" value={properties.length}/><Kpi icon={<Users/>} label="Clientes" value={clients.length}/><Kpi icon={<Euro/>} label="Precio medio" value={avg?avg.toLocaleString('es-ES')+' €':'—'}/><Kpi icon={<CalendarDays/>} label="Eventos" value={events.length}/></div></>}
