'use client';
import {useState} from 'react';
import {Building2,Users,ClipboardList,CalendarDays,Target,Newspaper,BarChart3,Settings,Plus,Search,LogOut,Menu,X} from 'lucide-react';
const modules=[['Inicio',BarChart3],['Inmuebles',Building2],['Clientes',Users],['Pedidos',ClipboardList],['Captación',Target],['Calendario',CalendarDays],['Noticias',Newspaper],['Estadísticas',BarChart3],['Configuración',Settings]];
export default function Home(){const [active,setActive]=useState('Inicio');const [open,setOpen]=useState(false);return <main className="shell"><aside className={open?'open':''}><div className="brand"><div className="mark">VB</div><div><b>VIVE BILBAO</b><span>INMOBILIARIO</span></div></div><nav>{modules.map(([n,I])=><button className={active===n?'sel':''} onClick={()=>{setActive(n);setOpen(false)}} key={n as string}><I size={18}/>{n as string}</button>)}</nav><div className="advisor"><div className="avatar">A</div><div><b>Asesor</b><span>Asesor inmobiliario</span></div><LogOut size={17}/></div></aside><section className="content"><header><button className="hamb" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><h1>{active}</h1><p>Vive Bilbao Inmobiliario · CRM central</p></div><div className="head-actions"><div className="search"><Search size={17}/><input placeholder="Buscar inmuebles, clientes..."/></div><button className="primary"><Plus size={17}/> Nuevo</button></div></header>{active==='Inicio'?<Dashboard/>:<Placeholder title={active}/>}</section></main>}
function Dashboard(){return <div className="page"><div className="welcome"><div><span className="eyebrow">PANEL DE CONTROL</span><h2>Buenos días 👋</h2><p>Todo lo que necesitas para gestionar tu actividad inmobiliaria.</p></div><button className="primary"><Plus size={17}/> Nueva operación</button></div><div className="stats"><Card title="Inmuebles activos" value="0" sub="Inventario compartido"/><Card title="Clientes" value="0" sub="Clientes asignados"/><Card title="Pedidos activos" value="0" sub="Demandas pendientes"/><Card title="Captaciones" value="0" sub="Oportunidades"/></div><div className="grid"><div className="panel"><div className="panel-title"><b>Actividad de hoy</b><span>Ver calendario</span></div><div className="empty"><CalendarDays size={30}/><b>No hay actividad registrada</b><span>Aquí aparecerán visitas, llamadas y tareas.</span></div></div><div className="panel"><div className="panel-title"><b>Últimos inmuebles</b><span>Ver todos</span></div><div className="empty"><Building2 size={30}/><b>Sin inmuebles todavía</b><span>Crea el primero para empezar.</span></div></div></div><div className="panel"><div className="panel-title"><b>Arquitectura del CRM</b><span>Vive Bilbao</span></div><div className="features"><Feature t="Usuarios y permisos" d="Administrador y asesores con datos personales y compartidos."/><Feature t="Base de datos central" d="Todos trabajan sobre la misma información online."/><Feature t="Cruces automáticos" d="Pedidos de clientes relacionados con inmuebles compatibles."/><Feature t="Captación" d="Seguimiento de propietarios y oportunidades."/></div></div></div>}
function Card({title,value,sub}:{title:string,value:string,sub:string}){return <div className="stat"><span>{title}</span><strong>{value}</strong><small>{sub}</small></div>}
function Feature({t,d}:{t:string,d:string}){return <div className="feature"><b>{t}</b><span>{d}</span></div>}
function Placeholder({title}:{title:string}){return <div className="page"><div className="panel big"><h2>{title}</h2><p>Este módulo está preparado para conectarse a la base de datos central de Vive Bilbao.</p><button className="primary"><Plus size={17}/> Crear registro</button></div></div>}
